server:
# Render automatically assigns a port, usually 8080 or based on PORT env var
# You generally don't need to specify 'port' here unless you have a specific requirement.

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # Recommended for production: checks schema, does NOT make changes
      dialect: org.hibernate.dialect.PostgreSQLDialect # Explicitly set for prod
    database-platform: org.hibernate.dialect.PostgreSQLDialect # <--- ADD THIS LINE
    show-sql: false # Do NOT show SQL queries in production logs
    properties:
      hibernate:
        format_sql: false # Do NOT format SQL in production logs

app:
  cors:
    allowed-origins: https://budget-tracker-app-ericpham.vercel.app # Your live Vercel frontend URL