server:
  port: 8080 # Port for transaction-service in development

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactiondb # Your local PostgreSQL
    username: postgres
    password: your_secure_password # Your local PostgreSQL password
    # driver-class-name is already in application.properties, no need to duplicate

  jpa:
    hibernate:
      ddl-auto: update # Good for development: updates schema automatically
      dialect: org.hibernate.dialect.PostgreSQLDialect # Explicitly set for dev
    show-sql: true # Show SQL queries in console for debugging
    properties:
      hibernate:
        format_sql: true # Format SQL nicely in console

app:
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000 # Your local React app