server:
# Render automatically assigns a port, usually 8080 or based on PORT env var
# You generally don't need to specify 'port' here unless you have a specific requirement.

spring:
  datasource:
    url: ${DATABASE_URL} # Render will provide this env var for Supabase pooler
    username: ${DATABASE_USERNAME} # Render will provide this env var
    password: ${DATABASE_PASSWORD} # Render will provide this env var
    # driver-class-name is already in application.properties, no need to duplicate

  jpa:
    hibernate:
      ddl-auto: validate # Recommended for production: checks schema, does NOT make changes
      dialect: org.hibernate.dialect.PostgreSQLDialect # Explicitly set for prod
    show-sql: false # Do NOT show SQL queries in production logs
    properties:
      hibernate:
        format_sql: false # Do NOT format SQL in production logs

app:
  cors:
    allowed-origins: https://budget-tracker-app-ericpham.vercel.app # Your live Vercel frontend URL