-- This script will be executed by PostgreSQL initdb to create the table

CREATE TABLE IF NOT EXISTS transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(19, 2) NOT NULL,
    type VARCHAR(255) NOT NULL, -- e.g., 'INCOME', 'EXPENSE'
    description VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP -- ONLY this column for timestamp
);

-- You might want to add indexes for performance
CREATE INDEX IF NOT EXISTS idx_transaction_type ON transaction (type);