server:
  port: 8081

# This service calls transaction-service locally
transaction:
  service:
    url: http://localhost:8080

app:
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000