# DO NOT set server.port (Render assigns it dynamically)

# For calling the deployed transaction-service
transaction:
  service:
    url: ${TRANSACTION_SERVICE_URL}

app:
  cors:
    allowed-origins: https://budget-tracker-app-ericpham.vercel.app